### ISSUE TITLE
Better observers support

### ISSUE THREAD

**Issue by deric** [deric/puppet-zookeeper#56]
Determine whether a server is an observer based on an attribute. e.g.:

```puppet
class {'zookeeper':
  role => 'observer', # default value would `master`
}
```
or using some kind of configuration hash:

```yaml
zookeeper:cluster:
  'foo.example.com':
     id: 1
     ip: "192.168.1.1"
     election_port: 2889
     leader_port: 3999
     role: 'master'
  'bar.example.com':
     id: 2
     ip: "192.168.1.2"
     election_port: 2889
     leader_port: 3999
     role: 'observer'
```
Related to #27, #29.
